# Generated by Django 2.2 on 2019-12-26 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Service Render', 'Service Render'), ('Service Provider', 'Service Provider')], default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
