# Generated by Django 2.2.4 on 2019-10-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Not Booked', 'Not Booked')], max_length=100, null=True),
        ),
    ]
