# Generated by Django 2.2 on 2020-01-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_i_will_be_available_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='pn',
            new_name='phone_number',
        ),
    ]
