# Generated by Django 2.2 on 2020-01-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200107_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('In need of service', 'In need of service'), ('Service Provider', 'Service Provider')], max_length=250),
        ),
    ]
