# Generated by Django 2.2.7 on 2019-12-12 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerender',
            name='render_email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerender',
            name='render_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
