# Generated by Django 2.2 on 2020-01-07 16:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0003_auto_20200107_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceRender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mycost', models.IntegerField()),
                ('render_name', models.CharField(max_length=250)),
                ('render_email', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('are_you_available', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='render_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='are_you_available',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='mycost',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='render_email',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='service_name',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='serviceRequest',
        ),
        migrations.AddField(
            model_name='servicerender',
            name='service_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='board.serviceProvider'),
        ),
    ]
