# Generated by Django 2.2 on 2020-01-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200107_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='inneedofservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mycost', models.IntegerField()),
                ('render_name', models.CharField(max_length=250)),
                ('render_email', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('service_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='board.serviceProvider')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='serviceRender',
        ),
    ]
